### ISSUE TITLE
Do not compile on Rust 1.93

### ISSUE THREAD

**Issue by Wybxc** [rutgersc/m3u8-rs#91]
```
   Compiling m3u8-rs v6.0.0
error[E0432]: unresolved import `crate::QuotedOrUnquoted`
 --> /Users/wybxc/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/m3u8-rs-6.0.0/src/playlist.rs:6:5
  |
6 | use crate::QuotedOrUnquoted;
  |     ^^^^^^^^^^^^^^^^^^^^^^^ no `QuotedOrUnquoted` in the root

error[E0282]: type annotations needed
   --> /Users/wybxc/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/m3u8-rs-6.0.0/src/playlist.rs:283:19
    |
283 |             .map(|c| c.try_into())
    |                   ^  - type must be known at this point
    |
help: consider giving this closure parameter an explicit type
    |
283 |             .map(|c: /* Type */| c.try_into())
    |                    ++++++++++++

error[E0282]: type annotations needed
    --> /Users/wybxc/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/m3u8-rs-6.0.0/src/playlist.rs:1091:16
     |
1091 |             if k.starts_with("X-") {
     |                ^ cannot infer type

Some errors have detailed explanations: E0282, E0432.
For more information about an error, try `rustc --explain E0282`.
error: could not compile `m3u8-rs` (lib) due to 3 previous errors
```
